(ns argon2.differential-test
  "This implementation against BouncyCastle's, over a spread of parameters.

  The five known-answer vectors in `argon2.core-test` pin three variants at
  two parameter sets. That leaves most of the parameter space untested, and
  the parts it leaves out are where Argon2's indexing rules actually branch:
  the reference-area size has four cases, the slice boundary behaves
  differently at index 0, multi-lane runs exercise cross-lane references that
  p=1 never reaches, and the second pass XORs where the first overwrites.

  So this runs both implementations over a deterministic spread and compares
  bytes. It is a separate source root, reached only by the `:oracle` alias,
  because BouncyCastle must never become a dependency of this library --
  it is what the library is CHECKED AGAINST, not something it builds on.

      clojure -M:oracle

  The parameters are generated by a fixed LCG rather than a random source. A
  differential test that picks new inputs each run reports a failure nobody
  can reproduce, which is worse than one that never fires."
  (:require [clojure.test :refer [deftest is testing]]
            [argon2.core :as a])
  (:import (org.bouncycastle.crypto.generators Argon2BytesGenerator)
           (org.bouncycastle.crypto.params Argon2Parameters Argon2Parameters$Builder)))

(def bc-type {:argon2d Argon2Parameters/ARGON2_d
              :argon2i Argon2Parameters/ARGON2_i
              :argon2id Argon2Parameters/ARGON2_id})

(defn bouncycastle
  [{:keys [type password salt secret associated-data
           parallelism memory-kib iterations tag-length]}]
  (let [ba (fn [v] (when v (byte-array (map unchecked-byte v))))
        b (cond-> (-> (Argon2Parameters$Builder. (bc-type type))
                      (.withSalt (ba salt))
                      (.withParallelism (int parallelism))
                      (.withMemoryAsKB (int memory-kib))
                      (.withIterations (int iterations))
                      (.withVersion Argon2Parameters/ARGON2_VERSION_13))
            (seq secret) (.withSecret (ba secret))
            (seq associated-data) (.withAdditional (ba associated-data)))
        gen (doto (Argon2BytesGenerator.) (.init (.build b)))
        out (byte-array tag-length)]
    (.generateBytes gen ^bytes (ba password) out)
    (a/hex out)))

(defn- lcg
  "A fixed byte sequence. Reproducibility matters more here than quality.

  `unchecked-*` because a 64-bit LCG is defined by its wraparound, and
  Clojure's checked arithmetic throws on exactly the overflow the recurrence
  depends on."
  [seed n]
  (->> (iterate (fn [x] (unchecked-add (unchecked-multiply x 6364136223846793005)
                                       1442695040888963407))
                (long seed))
       (drop 1) (take n)
       (mapv #(bit-and (unsigned-bit-shift-right % 24) 0xFF))))

(defn- cases []
  (for [type [:argon2d :argon2i :argon2id]
        [m t p] [;; the smallest legal arena, where reference-area-size hits
                 ;; its k-1 and index-0 edges on almost every step
                 [8 1 1] [8 3 1]
                 ;; multi-lane, so cross-lane references and the pass-0
                 ;; slice-0 same-lane restriction both get exercised
                 [32 1 2] [32 3 4] [64 2 4] [128 4 8]
                 ;; more than one address block per segment: 128 addresses
                 ;; is the counter boundary in the data-independent path
                 [2048 1 1] [2048 2 4]
                 ;; several passes, where the second-pass XOR rule applies
                 [256 5 2]]
        tau [4 32 64 65 100]]
    {:type type :parallelism p :memory-kib m :iterations t :tag-length tau
     :password (lcg (+ m t p tau) 19)
     :salt (lcg (+ 7777 m t p) 16)
     :secret (when (odd? (+ m tau)) (lcg (+ 31 t) 8))
     :associated-data (when (odd? (+ t p)) (lcg (+ 97 m) 13))}))

(deftest agrees-with-bouncycastle
  (let [cs (cases)]
    (is (<= 100 (count cs))
        "a differential suite this small would not be covering the branches it claims to")
    (doseq [c cs]
      (is (= (bouncycastle c) (a/hex (a/argon2! c)))
          (pr-str (select-keys c [:type :memory-kib :iterations :parallelism :tag-length]))))))

(deftest the-oracle-can-fail
  (testing "a differential test that cannot report a difference proves nothing"
    (let [c (first (cases))]
      (is (not= (bouncycastle c)
                (bouncycastle (update c :iterations inc)))
          "BouncyCastle itself must distinguish these, or the comparison above is vacuous"))))
